In [26]:
import numpy as np
import pandas as pd

In [27]:
population = pd.read_csv('population.csv')

population = population.rename(index=str, columns={"Country (or dependent territory)": "Country"})
population.head()

,Rank,Country (or dependent territory),Population,Date,% of world population,Source
0,1.0,China,1367470000,10/24/2014,19%,Official population clock
1,2.0,India,1261420000,10/24/2014,17.50%,Population clock
2,3.0,United States,318964000,10/24/2014,4.43%,Official population clock
3,4.0,Indonesia,252164800,7/1/2014,3.50%,Official estimate
4,5.0,Brazil,203337000,10/24/2014,2.83%,Official population clock

In [29]:
medals = pd.read_csv('medals.csv')
medals.head()

         Country  medals
0  United States    2827
1  Great Britain     880
2        Germany     855
3         France     840
4          Italy     701

In [30]:
results = pd.merge(population, medals, on="Country", how='left')
results = results.fillna(0)
results

,Rank,Country,Population,Date,% of world population,Source,medals
0,1.0,China,1367470000,10/24/2014,19%,Official population clock,608.0
1,2.0,India,1261420000,10/24/2014,17.50%,Population clock,28.0
2,3.0,United States,318964000,10/24/2014,4.43%,Official population clock,2827.0
3,4.0,Indonesia,252164800,7/1/2014,3.50%,Official estimate,32.0
4,5.0,Brazil,203337000,10/24/2014,2.83%,Official population clock,128.0
5,6.0,Pakistan,188020000,7/1/2014,2.61%,Official annual projection,10.0
6,7.0,Nigeria,178517000,7/1/2014,2.48%,UN projection[6],25.0
7,8.0,Bangladesh,157193000,10/24/2014,2.18%,Official population clock,0.0
8,9.0,Russian Federation,146149200,8/1/2014,2.03%,Official estimate,0.0
9,10.0,Japan,127090000,10/1/2014,1.77%,Monthly official estimate,497.0
10,11.0,Mexico,119713203,7/1/2014,1.66%,Official projection,69.0
11,12.0,Philippines,100440100,10/24/2014,1.40%,Official population clock,10.0
12,13.0,Viet Nam,89708900,7/1/2013,1.25%,Official estimate,0.0
13,14.0,Ethiopia,87952991,7/1/2014,1.22%,Official projection,53.0
14,15.0,Egypt,87371100,10/24/2014,1.21%,Official population clock,32.0
15,16.0,Germany,80767000,12/31/2013,1.12%,Official estimate,855.0
16,17.0,Iran,77838800,10/24/2014,1.08%,Official population clock,69.0
17,18.0,Turkey,76667864,12/31/2013,1.07%,Annual official estimate,91.0
18,19.0,Democratic Republic of Congo,69360000,7/1/2014,0.96%,UN projection,0.0
19,20.0,France,66048000,10/1/2014,0.92%,Monthly official estimate,840.0
20,21.0,Thailand,64871000,7/1/2014,0.90%,Official estimate,33.0
21,22.0,United Kingdom,64105654,7/1/2013,0.89%,Annual official estimate,0.0
22,23.0,Italy,60780377,4/30/2014,0.84%,Monthly official estimate,701.0
23,24.0,South Africa,54002000,7/1/2014,0.75%,Official estimate,86.0
24,25.0,Myanmar,51419420,3/29/2014,0.71%,Preliminary 2014 census result,0.0
25,26.0,South Korea,50423955,7/1/2014,0.70%,Official projection,337.0
26,27.0,Colombia,47832200,10/24/2014,0.67%,Official population clock,28.0
27,28.0,Tanzania,47421786,7/1/2014,0.66%,Official Projection,2.0
28,29.0,Spain,46507800,1/1/2014,0.63%,Annual official estimate,154.0
29,30.0,Ukraine,42981850,8/1/2014,0.60%,Monthly official estimate,129.0
...,...,...,...,...,...,...,...
217,214.0,* Faroe Islands* (Denmark),48723,8/1/2014,0.00%,Monthly official estimate,0.0
218,215.0,* Sint Maarten* (Netherlands),37429,1/1/2010,0.00%,Official estimate,0.0
219,216.0,Liechtenstein,37132,12/31/2013,0.00%,Semi annual official estimate,10.0
220,217.0,* Saint Martin* (France),36979,1/1/2010,0.00%,Official estimate,0.0
221,218.0,Monaco,36950,12/31/2013,0.00%,Annual official estimate,0.0
222,219.0,San Marino,32727,8/31/2014,0.00%,Monthly official estimate,0.0
223,220.0,* Turks and Caicos Islands* (UK),31458,1/25/2012,0.00%,2012 census result,0.0
224,221.0,* Gibraltar* (UK),30001,12/31/2012,0.00%,Annual official estimate,0.0
225,222.0,* British Virgin Islands* (UK),29537,7/1/2010,0.00%,Annual official estimate,0.0
226,223.0,* Åland Islands* (Finland),28875,9/30/2014,0.00%,Official estimate,0.0
227,224.0,* Caribbean Netherlands* (Netherlands),23296,1/1/2013,0.00%,Official estimate,0.0
228,225.0,Palau,20901,7/1/2013,0.00%,Annual official estimate,0.0
229,226.0,* Cook Islands* (NZ),14974,12/1/2011,0.00%,Final 2011 census result,0.0
230,227.0,* Anguilla* (UK),13452,5/11/2011,0.00%,Preliminary 2011 census result,0.0
231,228.0,* Wallis and Futuna* (France),13135,7/1/2013,0.00%,Annual official estimate,0.0
232,229.0,Tuvalu,11323,7/1/2013,0.00%,Annual official estimate,0.0
233,230.0,Nauru,10084,10/30/2011,0.00%,2011 census result,0.0
234,231.0,* Saint Barthélemy* (France),8938,1/1/2010,0.00%,Official estimate,0.0
235,232.0,* Saint Pierre and Miquelon* (France),6081,1/1/2010,0.00%,Official estimate,0.0
236,233.0,* Montserrat* (UK),4922,5/12/2011,0.00%,2011 census result,0.0
237,234.0,"* Saint Helena, Ascension and Tristan da Cunha...",4000,7/1/2014,0.00%,UN projection,0.0
238,235.0,* Falkland Islands* (UK),3000,7/1/2014,0.00%,UN projection,0.0
239,236.0,* Svalbard and Jan Mayen* (Norway),2655,9/1/2012,0.00%,Official estimate,0.0
240,237.0,* Norfolk Island* (Australia),2302,8/9/2011,0.00%,2011 census result,0.0
241,238.0,* Christmas Island* (Australia),2072,8/9/2011,0.00%,2011 census result,0.0
242,239.0,* Niue* (NZ),1613,9/10/2011,0.00%,Final 2011 census result,0.0
243,240.0,* Tokelau* (NZ),1411,10/18/2011,0.00%,Final 2011 census result,0.0
244,241.0,Vatican City,839,7/1/2012,0.00%,Official estimate,0.0
245,242.0,* Cocos (Keeling) Islands* (Australia),550,8/9/2011,0.00%,2011 census result,0.0
246,243.0,* Pitcairn Islands* (UK),56,2013,0.00%,Official estimate,0.0

In [34]:
population.shape

(247, 6)

In [35]:
results.shape

(247, 7)

In [36]:
results.to_csv("population_and_medals.csv", index=False)