In [1]:
import pandas as pd

In [2]:
#!ls ..
countries = pd.read_csv("countries.csv")
population_and_medals = pd.read_csv("population_and_medals.csv", encoding = "ISO-8859-1")

In [3]:
print(countries.shape)
print(population_and_medals.shape)

(225, 6)
(247, 7)

In [4]:
countries

,CountryName,CountryCode,ContinentCode,CenterLongitude,CenterLatitude,Population
0,Afghanistan,AF,AS,65.00,33.00,32526560
1,Albania,AL,EU,20.00,41.00,2896680
2,Algeria,DZ,AF,3.00,28.00,39666520
3,American Samoa,AS,OC,-170.50,-14.32,55540
4,Andorra,AD,EU,1.50,42.50,70470
5,Angola,AO,AF,18.50,-12.50,25021970
6,Anguilla,AI,NaN,-63.05,18.22,14610
7,Antigua and Barbuda,AG,NaN,-61.80,17.05,91820
8,Argentina,AR,SA,-64.00,-34.00,43416760
9,Armenia,AM,AS,45.00,40.00,3017710
10,Aruba,AW,NaN,-69.97,12.50,103890
11,Australia,AU,OC,135.00,-25.00,23968970
12,Austria,AT,EU,13.33,47.33,8544590
13,Azerbaijan,AZ,AS,47.50,40.50,9753970
14,Bahamas,BS,NaN,-76.00,24.00,388020
15,Bahrain,BH,AS,50.50,26.00,1377240
16,Bangladesh,BD,AS,90.00,24.00,160995640
17,Barbados,BB,NaN,-59.53,13.17,284220
18,Belarus,BY,EU,28.00,53.00,9495830
19,Belgium,BE,EU,4.00,50.83,11299190
20,Belize,BZ,NaN,-88.75,17.25,359290
21,Benin,BJ,AF,2.25,9.50,10879830
22,Bermuda,BM,NaN,-64.75,32.33,62000
23,Bhutan,BT,AS,90.50,27.50,774830
24,Bolivia,BO,SA,-65.00,-17.00,10724710
25,Bosnia and Herzegovina,BA,EU,17.83,44.25,3810420
26,Botswana,BW,AF,24.00,-22.00,2262490
27,Brazil,BR,SA,-55.00,-10.00,207847530
28,Brunei Darussalam,BN,AS,114.67,4.50,423190
29,Bulgaria,BG,EU,25.00,43.00,7149790
...,...,...,...,...,...,...
195,"Taiwan, Province of China",TW,AS,121.00,23.50,23381040
196,Tajikistan,TJ,AS,71.00,39.00,8481860
197,Tanzania,TZ,AF,35.00,-6.00,53470420
198,Thailand,TH,AS,100.00,15.00,67959360
199,Timor-Leste,TL,AS,125.72,-8.87,1184770
200,Togo,TG,AF,1.17,8.00,7304580
201,Tokelau,TK,OC,-171.75,-9.00,1250
202,Tonga,TO,OC,-175.00,-20.00,106170
203,Trinidad and Tobago,TT,NaN,-61.00,11.00,1360090
204,Tunisia,TN,AF,9.00,34.00,11253550
205,Turkey,TR,AS,35.00,39.00,78665830
206,Turkmenistan,TM,AS,60.00,40.00,5373500
207,Turks and Caicos Islands,TC,NaN,-71.58,21.73,34340
208,Tuvalu,TV,OC,178.00,-8.00,9920
209,Uganda,UG,AF,33.00,2.00,39032380
210,Ukraine,UA,EU,32.00,49.00,44823770
211,United Arab Emirates,AE,AS,54.00,24.00,9156960
212,United Kingdom,GB,EU,-4.50,54.00,64715810
213,United States,US,NaN,-98.00,38.00,321773630
214,United States Minor Outlying Islands,UM,OC,-175.00,10.00,106290
215,Uruguay,UY,SA,-56.00,-33.00,3431560
216,Uzbekistan,UZ,AS,64.00,41.00,29893490
217,Vanuatu,VU,OC,167.00,-16.00,264650
218,Venezuela,VE,SA,-66.00,8.00,31108080
219,Viet Nam,VN,AS,106.00,16.00,93447600
220,"Virgin Islands, British",VG,NaN,-64.50,18.50,30120
221,Wallis and Futuna,WF,OC,-177.00,-14.00,13150
222,Yemen,YE,AS,47.50,15.50,26832220
223,Zambia,ZM,AF,30.00,-15.00,16211770
224,Zimbabwe,ZW,AF,29.00,-19.00,15602750

In [5]:
population_and_medals.head()

,Rank,Country,Population,Date,% of world population,Source,medals
0,1.0,China,1367470000,10/24/2014,19%,Official population clock,608.0
1,2.0,India,1261420000,10/24/2014,17.50%,Population clock,28.0
2,3.0,United States,318964000,10/24/2014,4.43%,Official population clock,2827.0
3,4.0,Indonesia,252164800,7/1/2014,3.50%,Official estimate,32.0
4,5.0,Brazil,203337000,10/24/2014,2.83%,Official population clock,128.0

In [6]:
data_to_add = population_and_medals[['medals']]
data_to_add['CountryName']=population_and_medals['Country']
data_to_add.head()

C:\Users\zakar\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

   medals    CountryName
0   608.0          China
1    28.0          India
2  2827.0  United States
3    32.0      Indonesia
4   128.0         Brazil

In [7]:
results = pd.merge(countries, data_to_add, on="CountryName", how='left')
results['ContinentCode'] = results['ContinentCode'].fillna('NA')
results['medals'] = results['medals'].fillna(0)
results

,CountryName,CountryCode,ContinentCode,CenterLongitude,CenterLatitude,Population,medals
0,Afghanistan,AF,AS,65.00,33.00,32526560,2.0
1,Albania,AL,EU,20.00,41.00,2896680,0.0
2,Algeria,DZ,AF,3.00,28.00,39666520,17.0
3,American Samoa,AS,OC,-170.50,-14.32,55540,0.0
4,Andorra,AD,EU,1.50,42.50,70470,0.0
5,Angola,AO,AF,18.50,-12.50,25021970,0.0
6,Anguilla,AI,NA,-63.05,18.22,14610,0.0
7,Antigua and Barbuda,AG,NA,-61.80,17.05,91820,0.0
8,Argentina,AR,SA,-64.00,-34.00,43416760,74.0
9,Armenia,AM,AS,45.00,40.00,3017710,14.0
10,Aruba,AW,NA,-69.97,12.50,103890,0.0
11,Australia,AU,OC,135.00,-25.00,23968970,512.0
12,Austria,AT,EU,13.33,47.33,8544590,319.0
13,Azerbaijan,AZ,AS,47.50,40.50,9753970,43.0
14,Bahamas,BS,NA,-76.00,24.00,388020,14.0
15,Bahrain,BH,AS,50.50,26.00,1377240,3.0
16,Bangladesh,BD,AS,90.00,24.00,160995640,0.0
17,Barbados,BB,NA,-59.53,13.17,284220,1.0
18,Belarus,BY,EU,28.00,53.00,9495830,96.0
19,Belgium,BE,EU,4.00,50.83,11299190,154.0
20,Belize,BZ,NA,-88.75,17.25,359290,0.0
21,Benin,BJ,AF,2.25,9.50,10879830,0.0
22,Bermuda,BM,NA,-64.75,32.33,62000,0.0
23,Bhutan,BT,AS,90.50,27.50,774830,0.0
24,Bolivia,BO,SA,-65.00,-17.00,10724710,0.0
25,Bosnia and Herzegovina,BA,EU,17.83,44.25,3810420,0.0
26,Botswana,BW,AF,24.00,-22.00,2262490,1.0
27,Brazil,BR,SA,-55.00,-10.00,207847530,128.0
28,Brunei Darussalam,BN,AS,114.67,4.50,423190,0.0
29,Bulgaria,BG,EU,25.00,43.00,7149790,224.0
...,...,...,...,...,...,...,...
195,"Taiwan, Province of China",TW,AS,121.00,23.50,23381040,0.0
196,Tajikistan,TJ,AS,71.00,39.00,8481860,4.0
197,Tanzania,TZ,AF,35.00,-6.00,53470420,2.0
198,Thailand,TH,AS,100.00,15.00,67959360,33.0
199,Timor-Leste,TL,AS,125.72,-8.87,1184770,0.0
200,Togo,TG,AF,1.17,8.00,7304580,1.0
201,Tokelau,TK,OC,-171.75,-9.00,1250,0.0
202,Tonga,TO,OC,-175.00,-20.00,106170,1.0
203,Trinidad and Tobago,TT,NA,-61.00,11.00,1360090,19.0
204,Tunisia,TN,AF,9.00,34.00,11253550,13.0
205,Turkey,TR,AS,35.00,39.00,78665830,91.0
206,Turkmenistan,TM,AS,60.00,40.00,5373500,0.0
207,Turks and Caicos Islands,TC,NA,-71.58,21.73,34340,0.0
208,Tuvalu,TV,OC,178.00,-8.00,9920,0.0
209,Uganda,UG,AF,33.00,2.00,39032380,7.0
210,Ukraine,UA,EU,32.00,49.00,44823770,129.0
211,United Arab Emirates,AE,AS,54.00,24.00,9156960,2.0
212,United Kingdom,GB,EU,-4.50,54.00,64715810,0.0
213,United States,US,NA,-98.00,38.00,321773630,2827.0
214,United States Minor Outlying Islands,UM,OC,-175.00,10.00,106290,0.0
215,Uruguay,UY,SA,-56.00,-33.00,3431560,10.0
216,Uzbekistan,UZ,AS,64.00,41.00,29893490,32.0
217,Vanuatu,VU,OC,167.00,-16.00,264650,0.0
218,Venezuela,VE,SA,-66.00,8.00,31108080,15.0
219,Viet Nam,VN,AS,106.00,16.00,93447600,0.0
220,"Virgin Islands, British",VG,NA,-64.50,18.50,30120,0.0
221,Wallis and Futuna,WF,OC,-177.00,-14.00,13150,0.0
222,Yemen,YE,AS,47.50,15.50,26832220,0.0
223,Zambia,ZM,AF,30.00,-15.00,16211770,2.0
224,Zimbabwe,ZW,AF,29.00,-19.00,15602750,8.0

In [8]:
results.to_csv("d3_bubbles.csv", index=False, encoding='UTF-8')